# See https://github.com/alexa-pi/AlexaPi/wiki/Audio-setup-&-debugging
# to get a better idea of how to set things in here

# Level of log output
# default: INFO
# set to DEBUG for verbose logging
logging: INFO

sound:
  # Name of your microphone device in PortAudio
  # leave empty for default
  input_device: ""

  playback_handler: "vlc"

  # you can go here with alsa, pulse or others
  # keep blank for the best audio output selected by the underlying code
  #output: "pulseaudio"

  # if left empty, won't be passed to the underlying library / command if it supports it
  # if it doesn't 100% will be used
  default_volume: 80

  # Means the same as above, but is used for media (playing music for example)
  # Leave blank to use the same setting as for speech content
  media_default_volume:

  # Some devices clip off the beginning/end of audio files being played back. The
  # value is the number of seconds of silence to pad the beginning and end of the audio. Only
  # the sox handler supports this configuration option.
  playback_padding: 0

# Amazon Alexa settings
alexa:
  Client_ID: "amzn1.application-oa2-client.27cda2636ded4cb691b10133b3c75e9c"
  Client_Secret: "ccc56a200fa2ed05ab32196868131de92f7f3fa64b1614d95e937a18c99d818b"
  Device_Type_ID: "AlexaHerve"
  Security_Profile_Description: "AlexaHerve"
  Security_Profile_ID: "amzn1.application.a6ea67b75d0244e0baf844abe461d746"
  refresh_token: "Atzr|IwEBIAv3gN4hnbjlaixQz3uM-HQJwzK4Ztt6e21diebYmcRIbyGjT_cRUXAEN_yqS6cUw05BhpUeI5D37-Xs2IaufqQIPTuszwHoJpOuzV9Sn-PjPU4jZZQLiR7AUaBAhKbL1W8E3-V6T-mEWOSweXW_wL2ExF1wjOBeIiAhQAx82SpRni9yKzYr-p0qcOeFKo12fh4vTAynlfy79CcQtWivxL76NexCugjeDqXVGns9dMrNlIHPulCNOeCQcCydaVs8_ws9hZXbwnVZlCtFRx1PulHIOa2xi_XzfL6CYSQ7tVgf9qU8WaPmcSHpeXYvRZNnQhy0c5miHPHEN6MzDiOSFAABzwaSc9tDpMT0VTgSJatenygQcGeXmO4_fErJ7VRw7hlRc0MgfV5zkeffz-6SDH4qK8fBui56MgPRVvstAln-qsGUkLBSLogJrO0K9MGd_l4ljG2s8-2bB63A3LGwHMNrawXnbngSa_aH5LG_X2o7lThXq4PK5U_svXbSNhVYstocg9_-XgrATuHlmFzdf_W0rRJx_ttdZj41mvKNGymKkA"

# See https://github.com/alexa-pi/AlexaPi/wiki/Triggers for the description of these options
triggers:
  pocketsphinx:
    enabled: true
    voice_confirm: true

    phrase: "alexa"
    threshold: 1e-10

# Commands to run before and after an interaction begins. Leave empty to disable.
event_commands:

  # Example used to lower shairport-sync volume during interaction with alexa
  #     startup: "amixer set shairportvolume 100%"
  #     pre_interaction: "amixer set shairportvolume 10%-""
  #     post_interaction: "amixer set shairportvolume 10%+""
  # Note this assumes you have redirected shairport-syncs audio to a seperate softdevice
  # with control "shairportvolume". Example asound.conf avalible in the scripts folder

  # Command to run at the start of AlexaPi
  startup: ""

  # Command to run after a trigger is detected but before an interaction begins
  pre_interaction: ""

  # Command to run after the interaction has completed
  post_interaction: ""

  # Command to run during a clean shutdown of AlexaPi
  shutdown: ""

platform:
  # Name of your platform, e.g. raspberrypi, orangepi, desktop
  device: "dummy"

platforms:
  # common config for all platforms (if they support the options)
  # can be overriden in the the respective platform sections
  common:

  dummy:
